<a href="https://colab.research.google.com/github/VitorFRodrigues/Polo_Tech_Americanas/blob/main/Polo_Tech/Modulo_03/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" alt="Alternative text" />

A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e análise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

[Guia rápido de uso da biblioteca](https://numpy.org/devdocs/user/quickstart.html)

[Guia para iniciantes](https://numpy.org/devdocs/user/absolute_beginners.html)

___

Qual a diferença entre um numpy array e uma lista?

**numpy array:** armazena somente um tipo de dado (homogêneo), ocupando menos memória. É pensado para maior eficiência de cálculo.

**lista:** permite armazenar dados de vários tipos.

In [1]:
lista = ["a", 2, 2.4, True, [1,3], {"a:1"}]
lista

['a', 2, 2.4, True, [1, 3], {'a:1'}]

In [2]:
lista.append("Olá")
lista

['a', 2, 2.4, True, [1, 3], {'a:1'}, 'Olá']

Importando o numpy

In [3]:
import numpy as np

### Arrays em numpy

<img src = "https://numpy.org/devdocs/_images/np_array.png" />

#### Criando arrays

Pra criar arrays a partir de uma lista, basta utilizar a função **np.array()**

In [8]:
print(np.array([1, 2, 3]))

[1 2 3]


#### Atributos básicos pra um ndarray

In [13]:
_array = np.array([1, 2, 3, 4])

O formato dele

In [14]:
_array.shape

(4,)

Quantas dimensões ele tem

In [15]:
_array.ndim

1

Obter o tipo dos elementos do array (número, letra, ...)

In [16]:
_array.dtype

dtype('int64')

#### Tipo de dados em um ndarray

O dtype de um array do numpy pode ser controlado na hora que a gente cria.

In [18]:
_array = np.array([1, 2, 3, 4], dtype=np.float16)
print(_array)

[1. 2. 3. 4.]


In [19]:
_array.dtype

dtype('float16')

Mas quando a gente não define o tipo de dados?

In [20]:
py_array_2 = [1.0, 2, 3.0]
array_float = np.array(py_array_2)

print(array_float)
print(array_float.dtype)

[1. 2. 3.]
float64


In [24]:
py_array_string = [['a', 2, 3]]
array_str = np.array(py_array_string)

print(array_str)
print(array_str.dtype)

[['a' '2' '3']]
<U21


In [25]:
print(array_str.ndim)
print(array_str.shape)

2
(1, 3)


In [31]:
# E se o número for maior que a representação
np.array([1000], dtype=np.int8)

array([-24], dtype=int8)

#### Formas de inicializar Arrays

[numpy zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
# Tipo Inteiro
np.zeros((5,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

[numpy ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [33]:
np.ones((5,3), dtype=np.bool8)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

[numpy arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange)

In [36]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

[numpy linspace](https://numpy.org/devdocs/reference/generated/numpy.linspace.html#numpy-linspace)

Gerar um array com **linspace** pode ser bastante útil quando queremos lidar com algumas situações em gráficos.

[numpy random](https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random)

Array com valores aleatorios de uma distribuição uniforme entre 0 e 1 (exclusivo)

Array com inteiros aleatórios dentro de um intervalo

Fixando a seed: números aleatórios reproduzíveis

Também conseguimos trabalhar com **distribuições estatísticas de probabilidade**. Vejamos, por exemplo, como é possível gerar números aleatórios que obedeçam a uma distribuição normal.

<img src = "https://www.allaboutcircuits.com/uploads/articles/an-introduction-to-the-normal-distribution-in-electrical-engineerin-rk-aac-image1.jpg" />

Array com números aleatórios de uma distribuição normal (gaussiana)

__Uma pequena olhada...__

plotando distribuições com o seaborn

#### Operações simples

É possível fazer operações matemáticas **elemento a elemento** com os arrays, de forma bem simples:

Em numpy, as operações básicas (+, -, *, /) funcionam elemento a elemento

#### Funções numpy

Maior valor

Indice do elemento máximo

Menor valor

Indice do elemento minimo

Soma de todos os items

Media dos elementos

Desvio padrão

Ordenar a lista

Trocando o tipo dos dados nas lista com o .astype()

## Vamos praticar?

Em grupos, resolvam os exercícios a seguir.

**1.** Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

**2.** Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.